services:
  postgres:
    image: postgres:latest
    env_file: ./.env
    environment:
      - POSTGRES_PASSWORD=$POSTGRES_PASSWORD
      - POSTGRES_DB=$POSTGRES_DATABASE
      - POSTGRES_USER=$POSTGRES_USER
    ports:
      - $POSTGRES_LOCAL_PORT:5432
    volumes:
      - ./db-data/postgres:/var/lib/postgresql/data

